name: submit-azure-machine-learning-job

trigger:
- none


variables:
  service-connection: 'amldefault' # replace with your service connection name
  resource-group: 'aml_training' # replace with your resource group name
  workspace: 'dp100_training01' # replace with your workspace name

jobs:
- job: SubmitAzureMLJob
  displayName: Submit AzureML Job
  timeoutInMinutes: 300
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - task: UsePythonVersion@0
    displayName: Use Python >=3.8
    inputs:
      versionSpec: '>=3.8'

  - bash: |
      set -ex

      az version
      az extension add -n ml
      pip install azure-ai-ml azure-identity      
    displayName: 'Add AzureML Extension'

  - task: AzureCLI@1
    name: submit_azureml_job_task
    displayName: Submit AzureML Job Task
    inputs:
      azureSubscription: $(service-connection)
      workingDirectory: 'sdk/python/endpoints/online/managed'
      scriptLocation: inlineScript
      scriptType: bash
      inlineScript: |
        pwd
        ls
        tree .
        #tree /home/vsts/work/1/s
        # submit component job and get the run name hoge
        python deploy.py
        
