name: submit-azure-machine-learning-job

trigger:
- none


variables:
  service-connection: 'amldefault' # replace with your service connection name
  resource-group: 'aml_training' # replace with your resource group name
  workspace: 'dp100_training01' # replace with your workspace name

jobs:
- job: SubmitAzureMLJob
  displayName: Submit AzureML Job
  timeoutInMinutes: 300
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - task: UsePythonVersion@0
    displayName: Use Python >=3.8
    inputs:
      versionSpec: '>=3.8'

  - bash: |
      set -ex

      az version
      az extension add -n azure-cli-ml
    displayName: 'Add AzureML Extension'

  - task: AzureCLI@1
    name: submit_azureml_job_task
    displayName: Submit AzureML Job Task
    inputs:
      azureSubscription: $(service-connection)
      workingDirectory: 'modeldep_v1'
      scriptLocation: inlineScript
      scriptType: bash
      inlineScript: |
        az ml model deploy -n myservice3 -m credit_defaults_model:17 -m credit_defaults_model:16 --ic inf.json --dc dep.json --verbose --overwrite